version: '3.8' # このバージョン指定は警告が出ますが、現状は削除しなくても問題ありません

services:
  # Nginxサービスの設定
  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/ # ホストの./srcをコンテナの/var/wwwにマウント (Laravelプロジェクトのルート)
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  # PHP-FPMサービスの設定
  php:
    build: # Dockerfileのビルドコンテキストをプロジェクトルートに設定
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/ # ホストの./srcをコンテナの/var/wwwにマウント
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini # php.iniをマウント
    networks:
      - app-network
    environment: # Docker環境固有の変数のみを設定
      DB_HOST: mysql
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_pass
      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
    depends_on: # 依存関係を明示
      - mysql
      - mailhog

  # MySQLデータベースサービスの設定
  mysql:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      TZ: 'Asia/Tokyo'
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app-network

  # phpMyAdminサービスの設定
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_pass
    depends_on:
      - mysql
    ports:
      - 8080:80
    networks:
      - app-network

  # MailHogサービスの設定
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server
    networks:
      - app-network

# Dockerネットワークの定義
networks:
  app-network:
    driver: bridge
